<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="sparky">

    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.3"/>
    <xacro:property name="wheel_radius" value="0.036"/>
    <xacro:property name="base_wheel_gap" value="0.005"/>
    <xacro:property name="wheel_seperation" value="0.3"/>
    <xacro:property name="wheel_joint_offset" value="0.2"/>
    <xacro:property name="base_depth" value="0.4"/>

    <!-- <xacro:property name="name" value=""/> -->
        <material name="blue">
          <color rgba="0 0 0.8 1"/>
        </material>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
        <material name="red">
          <color rgba="0.8 0.0 0.0 1.0"/>
        </material>

    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m/12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m/12.0 * (w*w + h*h)}" iyz="0.0" izz="${m/12.0 * (w*w + d*d)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/> 
        </inertial>
    </xacro:macro>

    <xacro:macro name="wheel" params="prefix x y ">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${-(pi/2)} 0.0 0.0"/>              
                <geometry>
                    <mesh filename="package://sparky/meshes/${prefix}_link.STL"/>
                </geometry>
                <material name="red"/>                
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${-(pi/2)} 0.0 0.0"/>              
                <geometry>
                    <mesh filename="package://sparky/meshes/${prefix}_link.STL"/>    
                </geometry>    
            </collision>
            <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="0.076"/>                  
        </link>
        <joint name="${prefix}_wheel_joint" type="continuous">
            <axis xyz="0.0 1 0.0" rpy="0.0 0.0 0.0" />
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${((base_width/2)-0.04)*x} ${((base_depth/2)-0.11)*y} 0.0589" rpy="0.0 0.0 ${-(pi/2)} "/>           
        </joint>
    </xacro:macro>
    
    <xacro:wheel prefix="front_left" x="1" y="-1" />
    <xacro:wheel prefix="front_right" x="-1" y="-1" />
    <xacro:wheel prefix="back_left" x="1" y="1" />
    <xacro:wheel prefix="back_right" x="-1" y="1" />

    <link name="base_footprint">
        <xacro:box_inertia m="1" w="0.001" h="0.001" d="${base_depth}"/>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.001 0.001 0.001" />
            </geometry>
        </visual>
    </link>

    <link name="base_link">
        <light name='light_source1' type='spot'></light>
        <xacro:box_inertia m="1" w="0.4" h="0.4" d="0.4"/>
        <visual>
        <geometry>
        <mesh
          filename="package://sparky/meshes/base_link.STL" />
      </geometry>
          <material name="blue"/>
        </visual>
        <collision>
          <geometry>
            <mesh
                filename="package://sparky/meshes/base_link.STL" />
          </geometry>
        </collision>
    </link>
    <joint name="base_link_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius + 0.005}" rpy="0 0 ${pi/2}" />
        <parent link="base_footprint"/>
        <child link="base_link" />
    </joint>

    <!-- Lidar laser link -->
    <link name="lidar_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="-1.5708 0.0 0"/>
          <geometry>
            <mesh filename="package://sparky/meshes/lidar_link.STL" />
          </geometry>
        </visual>
        <collision>
          <origin xyz="0.0 0.0 0.0" rpy="-1.5708 0.0 0"/>
          <geometry>
            <mesh filename="package://sparky/meshes/lidar_link.STL" />
          </geometry>
        </collision>
    </link>
    <joint name="lidar_joint" type="fixed">
      <origin xyz="0.00128408400018751 -0.199342393380161 0.141250111826523" rpy="0 0 -1.5708" />
      <parent link="base_link" />
      <child link="lidar_link" />
      
    </joint>

    <link name="kinect_camera">
      <visual>
        <origin  xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="0.05 0.05 0.05"/>
          <!-- <mesh filename="package://sparky/meshes/kinect_camera.stl"/> -->
        </geometry> 
      </visual>
      <collision>
       <origin  xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="0.05 0.05 0.05"/>
          <!-- <mesh filename="package://sparky/meshes/kinect_camera.stl" /> -->
        </geometry>
      </collision>
    </link>
    <joint name="kinect_camera_joint" type="fixed">
        <origin xyz="0.0 -0.1 ${(base_height)}" rpy="0.0 0.0 -1.5708" />
        <parent link="base_link"/>
        <child link="kinect_camera"/>

    </joint>
  <xacro:include filename="$(find sparky)/urdf/sparky_gazebo_plugins.xacro"/>
  <xacro:include filename="$(find sparky)/urdf/sparky_sensor_plugins.xacro"/>
  <xacro:include filename="$(find sparky)/urdf/sparky_gazebo.material"/>
  <!-- <xacro:include filename="$(find sparky)/urdf/sparky_lights_plugin.xacro"/> -->
  
 
  
</robot>