obstacle_range: 2.5
raytrace_range: 3.0


robot_radius: 0.45
map_topic: /map
subscribe_to_updates: true

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: sensor_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

global_frame: map
robot_base_frame: base_footprint
always_send_full_costmap: true
map_type: costmap


transform_tolerance: 1 # seconds

static_map: true


obstacle_layer:
  enable: true
  observation_sources: base_scan
  base_scan: {sensor_frame: sensor_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}


inflation_layer:
  enable: true
  inflation_radius: 0.35
  cost_scaling_factor: 2.0

static_layer:
  enabled:              true

plugins:
  - {name: static_layer,            type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}