global_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.5
 
  static_map: true

  resolution: 0.050000
  occdist_scale:  0.01
  
  robot_base_frame: base_footprint
 
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

