local_costmap:
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5
  static_map: false
  rolling_window: true
  width: 30
  height: 30
 
  resolution: 0.050000
 
  
  global_frame: odom  #map
  robot_base_frame: base_link #was not there

  plugins:

    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
    # - {name: ultrasonic_layer,              type: "range_sensor_layer::RangeSensorLayer"}



ultrasonic_layer:
  enable: true
  observation_sources: base_scan
  base_scan: {sensor_frame: ultrasonic_sensor, data_type: sonar, topic: scan, marking: true, clearing: true}