#
shutdown_costmaps: false

controller_frequency: 40
controller_patience: 0.02

planner_frequency: 40
planner_patience: 5.0


yaw_goal_tolerance: 10   # earlier 1.0
xy_goal_tolerance: 10

# local planner - default is trajectory rollout

# base_local_planner: base_local_planner/TrajectoryPlannerROS

# base_local_planner: "dwa_local_planner/DWAPlannerROS"

# dwa_local_planner's forward_point_distance: 0